version: 2.1
jobs:
  build:
    working_directory: ~/django-google-oauth2
    docker:
      - image: circleci/python:2.7.15
    steps:
      - checkout
      - run:
          command: |
            python setup.py test
